Location.create!([
  {zone_id: 59, district: "Kota Setar"},
  {zone_id: 59, district: "Kubang Pasu"},
  {zone_id: 59, district: "Pokok Sena"},
  {zone_id: 60, district: "Pendang"},
  {zone_id: 60, district: "Kuala Muda"},
  {zone_id: 60, district: "Yan"},
  {zone_id: 61, district: "Padang Terap"},
  {zone_id: 61, district: "Sik"},
  {zone_id: 62, district: "Baling"},
  {zone_id: 63, district: "Seluruh Negeri Pulau Pinang"},
  {zone_id: 64, district: "Tapah,Slim River dan Tanjung Malim"},
  {zone_id: 65, district: "Ipoh"},
  {zone_id: 65, district: "Batu Gajah"},
  {zone_id: 65, district: "Kampar"},
  {zone_id: 65, district: "Sg. Siput dan Kuala Kangsar"},
  {zone_id: 66, district: "Pengkalan Hulu"},
  {zone_id: 66, district: "Grik dan Lenggong"},
  {zone_id: 67, district: "Gombak"},
  {zone_id: 67, district: "H.Selangor"},
  {zone_id: 67, district: "Rawang"},
  {zone_id: 67, district: "H.Langat"},
  {zone_id: 67, district: "Sepang,Petaling"},
  {zone_id: 67, district: "S.Alam"},
  {zone_id: 68, district: "Sabak Bernam"},
  {zone_id: 68, district: "Kuala Selangor"},
  {zone_id: 68, district: "Klang"},
  {zone_id: 68, district: "Kuala Langat"},
  {zone_id: 69, district: "Kuala Lumpur"},
  {zone_id: 70, district: "Putrajaya"},
  {zone_id: 71, district: "Labuan"},
  {zone_id: 72, district: "Jempol"},
  {zone_id: 72, district: "Tampin"},
  {zone_id: 73, district: "Port Dickson"},
  {zone_id: 73, district: "Seremban"},
  {zone_id: 73, district: "Kuala Pilah"},
  {zone_id: 73, district: "Jelebu"},
  {zone_id: 73, district: "Rembau"},
  {zone_id: 74, district: "Bandar Melaka"},
  {zone_id: 74, district: "Alor Gajah"},
  {zone_id: 74, district: "Jasin"},
  {zone_id: 74, district: "Masjid Tanah"},
  {zone_id: 74, district: "Merlimau"},
  {zone_id: 74, district: "Nyalas"},
  {zone_id: 75, district: "Pulau Aur dan Pemanggil"},
  {zone_id: 76, district: "Kota Tinggi"},
  {zone_id: 76, district: "Mersing"},
  {zone_id: 76, district: "Johor Bahru"},
  {zone_id: 77, district: "Kluang dan Pontian"},
  {zone_id: 78, district: "Kangar"},
  {zone_id: 78, district: "Padang Besar"},
  {zone_id: 78, district: "Arau"},
  {zone_id: 79, district: "Pulau Tioman"},
  {zone_id: 80, district: "Kuantan"},
  {zone_id: 80, district: "Pekan"},
  {zone_id: 80, district: "Rompin"},
  {zone_id: 80, district: "Muadzam Shah"},
  {zone_id: 81, district: "Maran"},
  {zone_id: 81, district: "Chenor"},
  {zone_id: 81, district: "Temerloh"},
  {zone_id: 81, district: "Bera"},
  {zone_id: 81, district: "Jerantut"},
  {zone_id: 82, district: "Bentong"},
  {zone_id: 82, district: "Raub"},
  {zone_id: 82, district: "Kuala Lipis"},
  {zone_id: 83, district: "Genting Sempah"},
  {zone_id: 83, district: "Janda Baik"},
  {zone_id: 83, district: "Bukit Tinggi"},
  {zone_id: 84, district: "Bukit Fraser"},
  {zone_id: 84, district: "Genting Higlands"},
  {zone_id: 84, district: "Cameron Higlands"},
  {zone_id: 85, district: "K.Bharu"},
  {zone_id: 85, district: "Bachok"},
  {zone_id: 85, district: "Pasir Puteh"},
  {zone_id: 85, district: "Tumpat"},
  {zone_id: 85, district: "Pasir Mas,Tnh. Merah"},
  {zone_id: 85, district: "Machang"},
  {zone_id: 85, district: "Kuala Krai"},
  {zone_id: 85, district: "Mukim Chiku"},
  {zone_id: 86, district: "Jeli"},
  {zone_id: 86, district: "Gua Musang (Mukim Galas"},
  {zone_id: 86, district: "Bertam)"},
  {zone_id: 87, district: "Kuala Terengganu"},
  {zone_id: 87, district: "Marang"},
  {zone_id: 88, district: "Besut"},
  {zone_id: 88, district: "Setiu"},
  {zone_id: 89, district: "Hulu Terengganu"},
  {zone_id: 90, district: "Kemaman Dungun"},
  {zone_id: 91, district: "Sandakan"},
  {zone_id: 91, district: "Bdr. Bkt. Garam"},
  {zone_id: 91, district: "Semawang"},
  {zone_id: 91, district: "Temanggong"},
  {zone_id: 91, district: "Tambisan"},
  {zone_id: 92, district: "Pinangah"},
  {zone_id: 92, district: "Terusan"},
  {zone_id: 92, district: "Beluran"},
  {zone_id: 92, district: "Kuamut"},
  {zone_id: 92, district: "Telupit"},
  {zone_id: 93, district: "Lahad Datu"},
  {zone_id: 93, district: "Kunak"},
  {zone_id: 93, district: "Silabukan"},
  {zone_id: 93, district: "Tungku"},
  {zone_id: 93, district: "Sahabat"},
  {zone_id: 93, district: "Semporna"},
  {zone_id: 94, district: "Tawau"},
  {zone_id: 94, district: "Balong"},
  {zone_id: 94, district: "Merotai"},
  {zone_id: 94, district: "Kalabakan"},
  {zone_id: 95, district: "Kudat"},
  {zone_id: 95, district: "Kota Marudu"},
  {zone_id: 95, district: "Pitas"},
  {zone_id: 95, district: "Pulau Banggi"},
  {zone_id: 96, district: "Gunung Kinabalu"},
  {zone_id: 97, district: "Papar"},
  {zone_id: 97, district: "Ranau"},
  {zone_id: 97, district: "Kota Belud"},
  {zone_id: 97, district: "Tuaran"},
  {zone_id: 97, district: "Penampang"},
  {zone_id: 97, district: "Kota Kinabalu"},
  {zone_id: 98, district: "Pensiangan"},
  {zone_id: 98, district: "Keningau"},
  {zone_id: 98, district: "Tambunan"},
  {zone_id: 98, district: "Nabawan"},
  {zone_id: 99, district: "Sipitang"},
  {zone_id: 99, district: "Membakut"},
  {zone_id: 99, district: "Beaufort"},
  {zone_id: 99, district: "Kuala Penyu"},
  {zone_id: 99, district: "Weston"},
  {zone_id: 99, district: "Tenom"},
  {zone_id: 99, district: "Long Pa Sia"},
  {zone_id: 100, district: "Limbang"},
  {zone_id: 100, district: "Sundar"},
  {zone_id: 100, district: "Terusan"},
  {zone_id: 100, district: "Lawas"},
  {zone_id: 101, district: "Niah"},
  {zone_id: 101, district: "Belaga"},
  {zone_id: 101, district: "Sibuti"},
  {zone_id: 101, district: "Miri"},
  {zone_id: 101, district: "Bekenu"},
  {zone_id: 101, district: "Marudi"},
  {zone_id: 102, district: "Song"},
  {zone_id: 102, district: "Belingan"},
  {zone_id: 102, district: "Sebauh"},
  {zone_id: 102, district: "Bintulu"},
  {zone_id: 102, district: "Tatau"},
  {zone_id: 102, district: "Kapit"},
  {zone_id: 103, district: "Igan"},
  {zone_id: 103, district: "Kanowit"},
  {zone_id: 103, district: "Sibu"},
  {zone_id: 103, district: "Dalat"},
  {zone_id: 103, district: "Oya"},
  {zone_id: 104, district: "Belawai"},
  {zone_id: 104, district: "Matu"},
  {zone_id: 104, district: "Daro"},
  {zone_id: 104, district: "Sarikei"},
  {zone_id: 104, district: "Julau"},
  {zone_id: 104, district: "Bitangor"},
  {zone_id: 104, district: "Rajang"},
  {zone_id: 105, district: "Kabong"},
  {zone_id: 105, district: "Lingga"},
  {zone_id: 105, district: "Sri Aman"},
  {zone_id: 105, district: "Engkelili"},
  {zone_id: 105, district: "Betong"},
  {zone_id: 105, district: "Spaoh"},
  {zone_id: 105, district: "Pusa"},
  {zone_id: 105, district: "Saratok"},
  {zone_id: 105, district: "Roban"},
  {zone_id: 105, district: "Debak"},
  {zone_id: 106, district: "Samarahan"},
  {zone_id: 106, district: "Simunjan"},
  {zone_id: 106, district: "Serian"},
  {zone_id: 106, district: "Sebuyau"},
  {zone_id: 106, district: "Meludam"},
  {zone_id: 107, district: "Kuching"},
  {zone_id: 107, district: "Bau"},
  {zone_id: 107, district: "Lundu"},
  {zone_id: 107, district: "Sematan"},
  {zone_id: 108, district: "Batu Pahat"},
  {zone_id: 108, district: "Muar"},
  {zone_id: 108, district: "Segamat"},
  {zone_id: 108, district: "Gemas"},
  {zone_id: 109, district: "Temengor dan Belum"},
  {zone_id: 110, district: "Teluk Intan"},
  {zone_id: 110, district: "Bagan Datoh"},
  {zone_id: 110, district: "Kg.Gajah"},
  {zone_id: 110, district: "Sri Iskandar"},
  {zone_id: 110, district: "Beruas"},
  {zone_id: 110, district: "Parit"},
  {zone_id: 110, district: "Lumut"},
  {zone_id: 110, district: "Setiawan dan Pulau Pangkor"},
  {zone_id: 111, district: "Selama"},
  {zone_id: 111, district: "Taiping"},
  {zone_id: 111, district: "Bagan Serai dan Parit Buntar"},
  {zone_id: 112, district: "Bukit Larut"},
  {zone_id: 113, district: "Kulim"},
  {zone_id: 113, district: "Bandar Bahru"},
  {zone_id: 114, district: "Langkawi"},
  {zone_id: 115, district: "Zon Khas"},
  {zone_id: 116, district: "Gunung Jerai"}
])
State.create!([
  {name: "Kedah", country_id: "MY"},
  {name: "Pulau Pinang", country_id: "MY"},
  {name: "Perak", country_id: "MY"},
  {name: "Selangor", country_id: "MY"},
  {name: "Kuala Lumpur", country_id: "MY"},
  {name: "Putrajaya", country_id: "MY"},
  {name: "Labuan", country_id: "MY"},
  {name: "Negeri Sembilan", country_id: "MY"},
  {name: "Melaka", country_id: "MY"},
  {name: "Johor", country_id: "MY"},
  {name: "Perlis", country_id: "MY"},
  {name: "Pahang", country_id: "MY"},
  {name: "Kelantan", country_id: "MY"},
  {name: "Terengganu", country_id: "MY"},
  {name: "Sabah", country_id: "MY"},
  {name: "Sarawak", country_id: "MY"}
])

Zone.create!([
  {code: "KDH01", state_id: 17, remarks: "Kota Setar, Kubang Pasu, Pokok Sena"},
  {code: "KDH02", state_id: 17, remarks: "Pendang, Kuala Muda, Yan"},
  {code: "KDH03", state_id: 17, remarks: "Padang Terap, Sik"},
  {code: "KDH04", state_id: 17, remarks: "Baling"},
  {code: "PNG01", state_id: 18, remarks: "Seluruh Negeri Pulau Pinang"},
  {code: "PRK01", state_id: 19, remarks: "Tapah,Slim River dan Tanjung Malim"},
  {code: "PRK02", state_id: 19, remarks: "Ipoh, Batu Gajah, Kampar, Sg. Siput dan Kuala Kangsar"},
  {code: "PRK03", state_id: 19, remarks: "Pengkalan Hulu, Grik dan Lenggong"},
  {code: "SGR01", state_id: 20, remarks: "Gombak, H.Selangor, Rawang, H.Langat, Sepang,Petaling, S.Alam"},
  {code: "SGR02", state_id: 20, remarks: "Sabak Bernam, Kuala Selangor, Klang, Kuala Langat"},
  {code: "SGR03", state_id: 21, remarks: "Kuala Lumpur"},
  {code: "SGR04", state_id: 22, remarks: "Putrajaya"},
  {code: "WLY02", state_id: 23, remarks: "Labuan"},
  {code: "NGS01", state_id: 24, remarks: "Jempol, Tampin"},
  {code: "NGS02", state_id: 24, remarks: "Port Dickson, Seremban, Kuala Pilah, Jelebu, Rembau"},
  {code: "MLK01", state_id: 25, remarks: "Bandar Melaka, Alor Gajah, Jasin, Masjid Tanah, Merlimau, Nyalas"},
  {code: "JHR01", state_id: 26, remarks: "Pulau Aur dan Pemanggil"},
  {code: "JHR02", state_id: 26, remarks: "Kota Tinggi, Mersing, Johor Bahru"},
  {code: "JHR03", state_id: 26, remarks: "Kluang dan Pontian"},
  {code: "PLS01", state_id: 27, remarks: "Kangar, Padang Besar, Arau"},
  {code: "PHG01", state_id: 28, remarks: "Pulau Tioman"},
  {code: "PHG02", state_id: 28, remarks: "Kuantan, Pekan, Rompin, Muadzam Shah"},
  {code: "PHG03", state_id: 28, remarks: "Maran, Chenor, Temerloh, Bera, Jerantut"},
  {code: "PHG04", state_id: 28, remarks: "Bentong, Raub, Kuala Lipis"},
  {code: "PHG05", state_id: 28, remarks: "Genting Sempah, Janda Baik, Bukit Tinggi"},
  {code: "PHG06", state_id: 28, remarks: "Bukit Fraser, Genting Higlands, Cameron Higlands"},
  {code: "KTN01", state_id: 29, remarks: "K.Bharu, Bachok, Pasir Puteh, Tumpat, Pasir Mas,Tnh. Merah, Machang, Kuala Krai, Mukim Chiku"},
  {code: "KTN03", state_id: 29, remarks: "Jeli, Gua Musang (Mukim Galas, Bertam)"},
  {code: "TRG01", state_id: 30, remarks: "Kuala Terengganu, Marang"},
  {code: "TRG02", state_id: 30, remarks: "Besut, Setiu"},
  {code: "TRG03", state_id: 30, remarks: "Hulu Terengganu"},
  {code: "TRG04", state_id: 30, remarks: "Kemaman Dungun"},
  {code: "SBH01", state_id: 31, remarks: "Sandakan, Bdr. Bkt. Garam, Semawang, Temanggong, Tambisan"},
  {code: "SBH02", state_id: 31, remarks: "Pinangah, Terusan, Beluran, Kuamut, Telupit"},
  {code: "SBH03", state_id: 31, remarks: "Lahad Datu, Kunak, Silabukan, Tungku, Sahabat, Semporna"},
  {code: "SBH04", state_id: 31, remarks: "Tawau, Balong, Merotai, Kalabakan"},
  {code: "SBH05", state_id: 31, remarks: "Kudat, Kota Marudu, Pitas, Pulau Banggi"},
  {code: "SBH06", state_id: 31, remarks: "Gunung Kinabalu"},
  {code: "SBH07", state_id: 31, remarks: "Papar, Ranau, Kota Belud, Tuaran, Penampang, Kota Kinabalu"},
  {code: "SBH08", state_id: 31, remarks: "Pensiangan, Keningau, Tambunan, Nabawan"},
  {code: "SBH09", state_id: 31, remarks: "Sipitang, Membakut, Beaufort, Kuala Penyu, Weston, Tenom, Long Pa Sia"},
  {code: "SWK01", state_id: 32, remarks: "Limbang, Sundar, Terusan, Lawas"},
  {code: "SWK02", state_id: 32, remarks: "Niah, Belaga, Sibuti, Miri, Bekenu, Marudi"},
  {code: "SWK03", state_id: 32, remarks: "Song, Belingan, Sebauh, Bintulu, Tatau, Kapit"},
  {code: "SWK04", state_id: 32, remarks: "Igan, Kanowit, Sibu, Dalat, Oya"},
  {code: "SWK05", state_id: 32, remarks: "Belawai, Matu, Daro, Sarikei, Julau, Bitangor, Rajang"},
  {code: "SWK06", state_id: 32, remarks: "Kabong, Lingga, Sri Aman, Engkelili, Betong, Spaoh, Pusa, Saratok, Roban, Debak"},
  {code: "SWK07", state_id: 32, remarks: "Samarahan, Simunjan, Serian, Sebuyau, Meludam"},
  {code: "SWK08", state_id: 32, remarks: "Kuching, Bau, Lundu, Sematan"},
  {code: "JHR04", state_id: 26, remarks: "Batu Pahat, Muar, Segamat, Gemas"},
  {code: "PRK04", state_id: 19, remarks: "Temengor dan Belum"},
  {code: "PRK05", state_id: 19, remarks: "Teluk Intan, Bagan Datoh, Kg.Gajah, Sri Iskandar, Beruas, Parit, Lumut, Setiawan dan Pulau Pangkor"},
  {code: "PRK06", state_id: 19, remarks: "Selama, Taiping, Bagan Serai dan Parit Buntar"},
  {code: "PRK07", state_id: 19, remarks: "Bukit Larut"},
  {code: "KDH05", state_id: 17, remarks: "Kulim, Bandar Bahru"},
  {code: "KDH06", state_id: 17, remarks: "Langkawi"},
  {code: "SWK09", state_id: 32, remarks: "Zon Khas"},
  {code: "KDH07", state_id: 17, remarks: "Gunung Jerai"}
])
